FROM {{ namespace }}/base-tools:{{ tag }}
MAINTAINER {{ maintainer }}

RUN mkdir -p /etc/snap/auto

# install Go and Snap
ADD install.sh /tmp/
RUN apt-get -y -t jessie-backports --no-install-recommends install golang \
    && bash /tmp/install.sh /etc/snap/auto \
    && rm /tmp/install.sh \
    && useradd --user-group snap \
    && usermod -a -G microservices snap \
    && chown -R snap: /etc/snap \
    && apt-get purge -y --auto-remove golang \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER snap
