[docker_logs_decoder]
type = "MultiDecoder"
subs = ['openstack_log_decoder', 'ovs_log_decoder']
cascade_strategy = "first-wins"
log_sub_errors = false

[docker_log_input]
type = "DockerLogInput"
decoder = "docker_logs_decoder"
log_decode_failures = false
