[openstack_log_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/os_openstack_log.lua"

[docker_log_input]
type = "DockerLogInput"
decoder = "openstack_log_decoder"
log_decode_failures = false
