FROM {{ namespace }}/base-tools:{{ tag }}
MAINTAINER {{ maintainer }}

ENV JAVA_HOME /usr/lib/jvm/java-1.7.0-openjdk-amd64/

RUN apt-get -y install --no-install-recommends openjdk-7-jre \
    && curl https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb -o /tmp/elasticsearch.deb \
    && dpkg -i /tmp/elasticsearch.deb \
    && rm -f /tmp/elasticsearch.deb \
    && apt-get clean

RUN usermod -a -G microservices elasticsearch \
    && chown -R elasticsearch: /usr/share/elasticsearch

# by default elasticsearch shell is /bin/false, we need
# /bin/bash to run elasticsearch as non-root
# https://discuss.elastic.co/t/running-as-non-root-user-service-wrapper-has-changed/7863
RUN usermod -s /bin/bash elasticsearch -d /usr/share/elasticsearch

USER elasticsearch
