FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

RUN apt-get -y install --no-install-recommends \
        cron \
        logrotate \
    && apt-get clean \
    && pip install --no-cache-dir elasticsearch-curator=={{ elasticsearch_curator_version }}
